# Generated by Django 4.0.6 on 2022-07-22 17:52

import datetime
from django.db import migrations, models
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('conficon_app', '0002_alter_icon_image_alter_result_zip_file'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='icon',
            options={'ordering': ['-created', 'name']},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['username']},
        ),
        migrations.AlterModelOptions(
            name='result',
            options={'ordering': ['-created', 'name']},
        ),
        migrations.AddField(
            model_name='icon',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='result',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2022, 7, 22, 17, 52, 5, 934420, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='icon',
            constraint=models.UniqueConstraint(fields=('user', 'name'), name='unique_icon_per_user'),
        ),
    ]
